backend:
  name: 'git-gateway'
  branch: 'master'

publish_mode: 'editorial_workflow'
media_folder: 'public/images/uploads'
public_folder: '/images/uploads'
local_backend: true

collections:
  - name: 'blog'
    label: 'StarUnity Blog'
    folder: 'src/pages/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: '../../layouts/PostsLayout.astro',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          lable: 'Language',
          name: 'lang',
          widget: 'select',
          options: ['en', 'zh-Hans'],
          default: 'zh-Hans',
        }
      - { label: 'Publish Date', name: 'pubDate', widget: 'datetime' }
      - {
          label: 'Latest Updates Date',
          name: 'updatedDate',
          widget: 'datetime',
        }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          summary: '{{fields.name}}',
          field: { label: Name, name: name, widget: string },
        }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
