backend:
  name: 'github'
  repo: 'starunity/starunity-blog'
  base_url: 'https://blog.starunity.dev'
  branch: 'master'

publish_mode: 'editorial_workflow'
media_folder: 'public/images/uploads'
public_folder: '/images/uploads'
local_backend: true

collections:
  - name: 'blog'
    label: 'StarUnity Blog'
    folder: 'src/pages/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
